import React,{useMemo,useState} from 'react';

const diseases=[
{name:'Bacterial blight',type:'Bacterial',risk:'High',signs:'Water-soaked lesions, dark spots, twig cankers, cracking and fruit spotting.',actions:['Use clean planting material and sanitize tools.','Remove and destroy heavily infected tissue; avoid moving contaminated material.','Improve canopy airflow and avoid prolonged leaf wetness.','Use only locally approved bactericides/copper products according to current labels and expert advice.']},
{name:'Alternaria fruit and leaf spot',type:'Fungal',risk:'High',signs:'Brown to dark lesions on leaves and fruit; lesions may enlarge under humid conditions.',actions:['Remove infected debris and improve orchard sanitation.','Keep canopy open through appropriate training and pruning.','Avoid overhead irrigation and extended wetness.','Use a registered fungicide program only after diagnosis and label verification.']},
{name:'Cercospora leaf spot',type:'Fungal',risk:'Medium',signs:'Small circular leaf spots that can coalesce and cause premature leaf drop.',actions:['Scout lower and inner canopy regularly.','Remove fallen infected leaves where practical.','Maintain balanced nutrition and airflow.','Follow current local fungicide recommendations if disease pressure warrants.']},
{name:'Anthracnose',type:'Fungal',risk:'Medium',signs:'Sunken dark fruit lesions and necrotic leaf/twig spots, often favored by humidity.',actions:['Harvest carefully to reduce wounds.','Remove mummified fruit and infected debris.','Reduce canopy humidity and fruit wetness.','Use a label-approved fungicide program guided by local extension advice.']},
{name:'Wilt complex',type:'Fungal/soil-borne',risk:'High',signs:'Progressive yellowing, drooping, vascular browning and plant decline.',actions:['Confirm diagnosis before treatment because multiple soil-borne agents can mimic wilt.','Improve drainage and avoid root injury.','Remove severely affected plants where advised.','Use healthy nursery stock and rotate/solarize soil where feasible.']},
{name:'Root rot',type:'Fungal/oomycete',risk:'High',signs:'Poor vigor, yellowing, root browning/decay and collapse in poorly drained soil.',actions:['Correct drainage and irrigation frequency.','Prevent standing water around trunks.','Inspect roots and confirm the causal organism.','Use only registered biological or chemical options suited to the confirmed pathogen.']},
{name:'Fruit rot',type:'Fungal',risk:'Medium',signs:'Softening, discoloration and decay, frequently entering through wounds or damaged tissue.',actions:['Minimize fruit injury from insects, pruning and harvest.','Remove infected fruit from the orchard.','Keep harvest containers clean and dry.','Use post-harvest measures only where locally approved.']},
{name:'Stem/collar canker',type:'Fungal/bacterial',risk:'Medium',signs:'Cankers, cracking, dieback or darkened tissue around stems/collar.',actions:['Prune back to healthy tissue with sanitized tools.','Avoid water accumulation at the collar.','Protect plants from mechanical injury.','Confirm pathogen before applying a targeted treatment.']},
{name:'Nutrient-deficiency lookalikes',type:'Physiological',risk:'Medium',signs:'Chlorosis, marginal scorching, poor growth or malformed fruit without a clear pathogen pattern.',actions:['Use soil and leaf testing rather than guessing from color alone.','Review pH, irrigation and root health.','Correct the confirmed deficiency gradually and avoid over-fertilization.']}
];
const pests=[['Fruit borer / anar butterfly','Larvae bore into fruit; frass and damaged arils are common signs.','Sanitation, bagging where practical, removal of infested fruit, pheromone/light monitoring where locally recommended.'],['Thrips','Scarring, bronzing and distortion of tender growth/fruit surfaces.','Scout flowers and tender flush; manage weeds and use selective, label-approved options when thresholds justify.'],['Aphids','Clusters on tender shoots; curling, honeydew and sooty mold may occur.','Encourage beneficial insects; avoid unnecessary broad-spectrum sprays.'],['Mealybugs','Cottony colonies, honeydew and weak shoot growth.','Control ants, prune hotspots, use biological/registered controls according to local guidance.'],['Whiteflies','Adults fly from disturbed foliage; nymphs and honeydew occur beneath leaves.','Monitor undersides of leaves and preserve natural enemies.'],['Mites','Fine stippling, bronzing and possible webbing under hot/dry conditions.','Monitor leaf surfaces, reduce plant stress and use registered miticides only when warranted.']];
const stages=['Dormancy / pruning','Bahar initiation','Flowering','Fruit set','Fruit development','Maturity & harvest'];
const activities=[['Today','Scout 20 representative plants','Crop health'],['Tomorrow','Check drip emitters and soil moisture','Irrigation'],['This week','Review nutrition against soil/leaf tests','Nutrition'],['This week','Remove fallen/mummified fruit','Sanitation']];
function Card({children,className=''}){return <div className={'card '+className}>{children}</div>}
function App(){const [tab,setTab]=useState('Dashboard');const [query,setQuery]=useState('');const [selected,setSelected]=useState(null);const filtered=useMemo(()=>diseases.filter(d=>(d.name+d.type+d.signs).toLowerCase().includes(query.toLowerCase())),[query]);
const nav=['Dashboard','Farm','Crop Calendar','Diseases','Pests','Nutrition','Irrigation','Scouting','Economics','Reports'];
return <div className="app"><aside><div className="brand"><span>◈</span><div><b>PomegranateOS</b><small>Farm intelligence</small></div></div><div className="farm-chip">🍎 <div><strong>Shree Pomegranate Farm</strong><small>Demo farm · 8.5 acres</small></div></div><nav>{nav.map(n=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}>{n==='Dashboard'?'⌂':n==='Farm'?'▣':n==='Crop Calendar'?'◷':n==='Diseases'?'✚':n==='Pests'?'◉':n==='Nutrition'?'◇':n==='Irrigation'?'≈':n==='Scouting'?'⌕':n==='Economics'?'₹':'▤'}<span>{n}</span></button>)}</nav><div className="side-foot">● System healthy<br/><small>v1.0 · Demo mode</small></div></aside><main><header><div><span className="eyebrow">FARM COMMAND CENTER</span><h1>{tab}</h1></div><div className="header-actions"><span className="weather">☀ 29°C · 62% RH</span><button className="primary">＋ Add record</button></div></header>{tab==='Dashboard'?<Dashboard/>:tab==='Diseases'?<DiseasePage query={query} setQuery={setQuery} filtered={filtered} selected={selected} setSelected={setSelected}/>:tab==='Pests'?<PestPage/>:<Module title={tab} />}</main></div>}
function Dashboard(){return <><section className="hero"><div><span className="pill">● LOW-MODERATE RISK</span><h2>Your orchard, at a glance.</h2><p>Stay ahead of disease, water stress and crop tasks with one operating view.</p></div><div className="hero-orchard">🍎<span>1,820<br/><small>trees monitored</small></span></div></section><div className="stats"><Card><small>ORCHARD HEALTH</small><strong>87%</strong><span className="up">↑ 4.2% this week</span></Card><Card><small>ACTIVE ALERTS</small><strong>3</strong><span className="warn">2 crop · 1 weather</span></Card><Card><small>EST. YIELD</small><strong>7.8 t</strong><span>Current season</span></Card><Card><small>SEASON SALES</small><strong>₹3.42L</strong><span>↑ 12% vs last season</span></Card></div><div className="grid"><Card className="wide"><div className="card-head"><div><small>FIELD PULSE</small><h3>Crop stage & tasks</h3></div><span className="badge">Fruit development</span></div><div className="timeline">{stages.map((s,i)=><div className={i===4?'stage current':'stage'} key={s}><i>{i<4?'✓':i===4?'●':'○'}</i><span>{s}</span></div>)}</div><div className="task-list">{activities.map(a=><div className="task" key={a[1]}><div><small>{a[0]}</small><strong>{a[1]}</strong></div><span>{a[2]}</span><button>Open</button></div>)}</div></Card><Card><small>DISEASE WATCH</small><h3>Top risks</h3>{diseases.slice(0,4).map(d=><div className="risk" key={d.name}><div><strong>{d.name}</strong><small>{d.type}</small></div><span className={'risk-'+d.risk.toLowerCase()}>{d.risk}</span></div>)}<button className="link" onClick={()=>location.reload()}>View knowledge base →</button></Card></div><div className="grid"><Card><small>WATER STATUS</small><div className="water"><strong>68%</strong><span>Soil moisture</span></div><div className="progress"><i style={{width:'68%'}}/></div><p>Next irrigation window: <b>Tomorrow 06:00</b></p></Card><Card><small>RECENT SCOUTING</small><h3>12 observations</h3><p>8 healthy · 3 minor issues · 1 needs review</p><div className="mini-bar"><i/><i/><i/><i/></div></Card><Card><small>NET SEASON MARGIN</small><h3>₹1.86L</h3><p>After recorded inputs and harvest costs</p><span className="up">↑ 8.7%</span></Card></div></>}
function DiseasePage({query,setQuery,filtered,selected,setSelected}){return <><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search diseases, symptoms or type…"/><select><option>All risk levels</option><option>High</option><option>Medium</option></select></div><div className="notice">⚕ <div><b>Diagnosis first.</b> Similar symptoms can have different causes. Use scouting evidence and, when uncertain, obtain laboratory or expert confirmation before treatment.</div></div><div className="disease-grid">{filtered.map(d=><Card key={d.name}><div className="disease-top"><span className="disease-icon">✚</span><span className={'risk-pill '+d.risk.toLowerCase()}>{d.risk}</span></div><small>{d.type}</small><h3>{d.name}</h3><p>{d.signs}</p><button className="secondary" onClick={()=>setSelected(d)}>View management →</button></Card>)}</div>{selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="pill">{selected.type} · {selected.risk} risk</span><h2>{selected.name}</h2><p>{selected.signs}</p><h3>Integrated management</h3><ol>{selected.actions.map(a=><li key={a}>{a}</li>)}</ol><div className="notice">Treatment products, rates and pre-harvest intervals must follow the current local label and agricultural authority guidance.</div></div></div>}</>}
function PestPage(){return <><div className="hero small"><div><span className="pill">IPM</span><h2>Pest intelligence</h2><p>Scout first, identify accurately, then use the least disruptive effective intervention.</p></div></div><div className="disease-grid">{pests.map(p=><Card key={p[0]}><span className="disease-icon">◉</span><h3>{p[0]}</h3><p><b>Signs:</b> {p[1]}</p><p><b>Management:</b> {p[2]}</p><button className="secondary">Add scouting record</button></Card>)}</div></>}
function Module({title}){const content={Farm:['8.5 acres','1,820 trees','Bhagwa variety','Drip irrigated'], 'Crop Calendar':['6 stages tracked','14 upcoming tasks','3 overdue checks','Bahar: Hasta'],Nutrition:['Soil test: 6.8 pH','NPK plan active','2 micronutrient checks','Fertigation enabled'],Irrigation:['68% soil moisture','Drip system active','Next: tomorrow 06:00','No leak alert'],Scouting:['12 observations','8 healthy','3 minor issues','1 review needed'],Economics:['₹1.56L inputs','₹3.42L sales','₹1.86L margin','Yield: 7.8 t'],Reports:['Season report ready','Disease log ready','Input ledger ready','Harvest report ready']}[title]||['Module ready','Connect farm data','Configure alerts','Start recording'];return <div className="module"><div className="hero small"><div><span className="pill">MODULE</span><h2>{title} workspace</h2><p>A structured operating area for your orchard records and decisions.</p></div></div><div className="stats">{content.map((x,i)=><Card key={x}><small>{['CURRENT','TRACKED','STATUS','NEXT ACTION'][i]}</small><strong>{x.split(' · ')[0]}</strong><span>{x.includes('·')?x.split('·').slice(1).join('·'):['Live data ready','Recorded in season log','Review when needed',''][i]}</span></Card>)}</div><Card><h3>Recommended next actions</h3><div className="task-list">{activities.map(a=><div className="task" key={a[1]}><div><small>{a[0]}</small><strong>{a[1]}</strong></div><span>{a[2]}</span><button>Open</button></div>)}</div></Card></div>}
export default App;
