create extension if not exists pgcrypto;
create table if not exists public.farms(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,location text,area_acres numeric,soil_type text,notes text,created_at timestamptz default now());
create table if not exists public.plots(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id) on delete cascade,name text not null,area_acres numeric,notes text,created_at timestamptz default now());
create table if not exists public.crop_cycles(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id) on delete cascade,plot_id uuid references public.plots(id) on delete set null,crop_name text not null,variety text,planted_on date not null,expected_harvest_on date,harvested_on date,plant_count int,status text default 'active',notes text,created_at timestamptz default now());
create table if not exists public.activities(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id) on delete cascade,crop_cycle_id uuid references public.crop_cycles(id) on delete set null,plot_id uuid references public.plots(id) on delete set null,activity_type text not null,activity_date date not null,title text not null,quantity numeric,unit text,product text,reason text,weather text,cost numeric default 0,notes text,created_at timestamptz default now());
create table if not exists public.harvests(id uuid primary key default gen_random_uuid(),crop_cycle_id uuid not null references public.crop_cycles(id) on delete cascade,harvest_date date not null,quantity numeric not null,unit text not null,grade text,selling_price numeric,buyer text,notes text,created_at timestamptz default now());
create table if not exists public.expenses(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id) on delete cascade,expense_date date not null,category text not null,description text not null,amount numeric not null,vendor text,notes text,created_at timestamptz default now());
create table if not exists public.tasks(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id) on delete cascade,crop_cycle_id uuid references public.crop_cycles(id) on delete set null,title text not null,due_date date,priority text default 'medium',status text default 'open',notes text,created_at timestamptz default now());
create table if not exists public.ai_notes(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id) on delete cascade,category text,prompt text,response text,created_at timestamptz default now());

do $$declare t text;begin for t in select unnest(array['farms','plots','crop_cycles','activities','harvests','expenses','tasks','ai_notes']) loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy farm_owner on public.farms for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy plot_owner on public.plots for all to authenticated using(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid())) with check(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid()));
create policy cycle_owner on public.crop_cycles for all to authenticated using(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid())) with check(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid()));
create policy activity_owner on public.activities for all to authenticated using(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid())) with check(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid()));
create policy harvest_owner on public.harvests for all to authenticated using(exists(select 1 from crop_cycles c join farms f on f.id=c.farm_id where c.id=crop_cycle_id and f.user_id=auth.uid())) with check(exists(select 1 from crop_cycles c join farms f on f.id=c.farm_id where c.id=crop_cycle_id and f.user_id=auth.uid()));
create policy expense_owner on public.expenses for all to authenticated using(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid())) with check(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid()));
create policy task_owner on public.tasks for all to authenticated using(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid())) with check(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid()));
create policy ai_owner on public.ai_notes for all to authenticated using(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid())) with check(exists(select 1 from farms f where f.id=farm_id and f.user_id=auth.uid()));