import "./DecisionEvidence.css";

export default function DecisionEvidence({ decision }) {
  if (!decision) return null;
  const risks = decision.risks || [];
  const profile = decision.cropProfile;
  return (
    <section className="decision-evidence">
      <div className="evidence-head"><div><span>EXPLAINABILITY</span><h3>Why am I seeing this?</h3><p>Each alert is linked to a live measurement and the crop profile used by the decision engine.</p></div>{profile && <strong>{profile.name} profile</strong>}</div>
      {risks.length ? <div className="evidence-list">{risks.map((risk) => <article className="evidence-card" key={risk.type + risk.signal}>
        <div className="evidence-icon">{risk.type === "vegetation" ? "🛰️" : risk.type === "soil" ? "🧪" : risk.type === "heat" ? "🌡️" : risk.type === "rain" ? "🌧️" : "⚠️"}</div>
        <div><strong>{risk.signal}</strong><p>{risk.reason}</p>{risk.evidence && <small>Evidence: {risk.evidence.metric} {risk.evidence.comparison} {String(risk.evidence.threshold)}{risk.evidence.value !== undefined ? " · observed " + risk.evidence.value : ""}</small>}</div>
      </article>)}</div> : <div className="evidence-none">No elevated signals were generated by the current rule set.</div>}
      <div className="evidence-disclaimer">Decision support only. Verify important conditions in the field before changing irrigation, nutrition or crop-protection practices.</div>
    </section>
  );
}