CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS farmers(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,phone TEXT UNIQUE,email TEXT UNIQUE,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS farms(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),farmer_id UUID REFERENCES farmers(id),name TEXT NOT NULL,area_acres NUMERIC(10,2),village TEXT,district TEXT,state TEXT,variety TEXT,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS plots(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),farm_id UUID REFERENCES farms(id) ON DELETE CASCADE,name TEXT NOT NULL,area_acres NUMERIC(10,2),tree_count INT,planting_date DATE,irrigation_type TEXT,soil_type TEXT);
CREATE TABLE IF NOT EXISTS crop_cycles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),plot_id UUID REFERENCES plots(id) ON DELETE CASCADE,season TEXT,stage TEXT,start_date DATE,end_date DATE,status TEXT DEFAULT 'active');
CREATE TABLE IF NOT EXISTS diseases(id TEXT PRIMARY KEY,name TEXT NOT NULL,type TEXT,risk TEXT,description TEXT,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS disease_symptoms(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),disease_id TEXT REFERENCES diseases(id) ON DELETE CASCADE,symptom TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS disease_management(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),disease_id TEXT REFERENCES diseases(id) ON DELETE CASCADE,method TEXT NOT NULL,details TEXT NOT NULL,source TEXT);
CREATE TABLE IF NOT EXISTS pests(id TEXT PRIMARY KEY,name TEXT NOT NULL,signs TEXT,ipm TEXT);
CREATE TABLE IF NOT EXISTS farm_activities(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),plot_id UUID REFERENCES plots(id) ON DELETE CASCADE,title TEXT NOT NULL,category TEXT,due_date DATE,status TEXT DEFAULT 'planned',notes TEXT);
CREATE TABLE IF NOT EXISTS irrigation_records(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),plot_id UUID REFERENCES plots(id) ON DELETE CASCADE,recorded_at TIMESTAMPTZ DEFAULT now(),duration_minutes INT,water_liters NUMERIC,soil_moisture NUMERIC,notes TEXT);
CREATE TABLE IF NOT EXISTS scouting_records(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),plot_id UUID REFERENCES plots(id) ON DELETE CASCADE,scouted_at TIMESTAMPTZ DEFAULT now(),plants_checked INT,healthy INT,issue TEXT,severity TEXT,notes TEXT);
CREATE TABLE IF NOT EXISTS disease_reports(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),plot_id UUID REFERENCES plots(id),disease_id TEXT REFERENCES diseases(id),reported_at TIMESTAMPTZ DEFAULT now(),confidence NUMERIC,notes TEXT,status TEXT DEFAULT 'open');
CREATE TABLE IF NOT EXISTS expenses(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),farm_id UUID REFERENCES farms(id),category TEXT,amount NUMERIC(12,2),spent_on DATE,description TEXT);
CREATE TABLE IF NOT EXISTS harvests(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),plot_id UUID REFERENCES plots(id),harvest_date DATE,quantity_kg NUMERIC(12,2),grade TEXT,price_per_kg NUMERIC(10,2));
CREATE TABLE IF NOT EXISTS sales(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),farm_id UUID REFERENCES farms(id),sale_date DATE,quantity_kg NUMERIC(12,2),price_per_kg NUMERIC(10,2),buyer TEXT);
CREATE TABLE IF NOT EXISTS notifications(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),farm_id UUID REFERENCES farms(id),title TEXT,message TEXT,severity TEXT,read BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_activity_due ON farm_activities(due_date,status);
CREATE INDEX IF NOT EXISTS idx_reports_plot ON disease_reports(plot_id,reported_at DESC);
